### ISSUE TITLE
Peak calling error in SAMTools

### ISSUE THREAD

**Issue by chandni177** [ctlab/quant3p#2]
Hi,

I've been working on using quant3p for RNA-Seq data aligned using STAR. (Command below):

STAR --runThreadN 16 --genomeDir ./Genome --readFilesIn Barcode1.fastq --outFileNamePrefix MapBarcode1. --quantMode TranscriptomeSAM --outFilterMismatchNmax 6 --outFilterMultimapNmax 1

quant3p -n test -g gencode.vM6.annotation.gtf MapBarcode1.Aligned.toTranscriptome.out.bam

However, I always get the error SAMTools invalid BAM binary header (this is not a BAM file)

To investigate further, I tried running just the macs2-stranded on the same data and I still cannot get it to run.
I figured it might be a problem with the BAM file from STAR (MapBarcode1.Aligned.toTranscriptome.out.bam)
and I re-added the Header information into the BAM file. The error persisted.

Have you, by any chance, come across this? It would be great if you can help me out.

Thanks a lot,
Chandni

**Comment by assaron** [comment]
Hi, Chandni, 

quant3p (as does htseq) uses genomic alignment, not transcriptomic. So simple Aligned.out.bam should be used, not the Aligned.toTranscriptome one.

Also, here is the command we are using for STAR:  "--outFilterMultimapNmax 15 --outFilterMismatchNmax 6  --outSAMstrandField All --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM" may be outSAMstrandField and outSAMtype options can make a difference.

**Comment by chandni177** [comment]
I see,
That helps. I will try it out.

Thanks a lot!
Chandni

**Comment by chandni177** [comment]
I tried the command that you suggested and used the Aligned.out.bam as
input to quant3p :

quant3p/bin/macs2-stranded -n testQuant3p MapBarcode1.Aligned.out.sorted.bam
Attached is the output (log). I still get the same error.

Thanks once again for helping out,
Chandni

**Comment by assaron** [comment]
Chandni, you didn't attach the log file.

Also, it would be great if you shared the resulting bam-file. For example, you can run
`samtools view -h MapBarcode1.Aligned.out.sorted.bam | head -n 10000 | samtools view -bS - > MapBarcode1.Aligned.out.sorted.h10K.bam` and send me `MapBarcode1.Aligned.out.sorted.h10K.bam`.

**Comment by chandni177** [comment]
I attached it on Gmail but I guess Github didn't take it.

Can I send it to you to a particular email address?

Thanks!
Chandni

**Comment by assaron** [comment]
The problem is in macs2-stranded expecting at least two bam files internally. Will fix soon.

**Comment by chandni177** [comment]
Thanks for your help!
Working perfectly fine with multiple files.
